<a href="https://colab.research.google.com/github/maryemmohamed9/Python-For-Data-Analysis/blob/main/Customer_Churn_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Read Data

In [62]:
import numpy as np
import pandas as pd
df=pd.read_excel('02 Customer Churn-Dataset.xlsx')
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     StreamingTV StreamingMovies        Contract PaperlessBilling  \
0             No              No  Month-to-month              Yes   
1             No              No        One year               No   
2             No              No  Month-to-month              Yes   
3             No              No        One year               No   
4             No              No  Month-to-month              Yes   
...          ...             ...             ...              ...   
7038         Yes             Yes        One year              Yes   
7039         Yes             Yes        One year              Yes   
7040          No              No  Month-to-month              Yes   
7041          No              No  Month-to-month              Yes   
7042         Yes             Yes        Two year              Yes   

                  PaymentMethod MonthlyCharges TotalCharges numAdminTickets  \
0              Electronic check          29.85        29.85               0   
1                  Mailed check          56.95       1889.5               0   
2                  Mailed check          53.85       108.15               0   
3     Bank transfer (automatic)          42.30      1840.75               0   
4              Electronic check          70.70       151.65               0   
...                         ...            ...          ...             ...   
7038               Mailed check          84.80       1990.5               0   
7039    Credit card (automatic)         103.20       7362.9               0   
7040           Electronic check          29.60       346.45               0   
7041               Mailed check          74.40        306.6               0   
7042  Bank transfer (automatic)         105.65       6844.5               2   

      numTechTickets Churn  
0                  0    No  
1                  0    No  
2                  0   Yes  
3                  3    No  
4                  0   Yes  
...              ...   ...  
7038               0    No  
7039               5    No  
7040               0    No  
7041               0   Yes  
7042               0    No  

[7043 rows x 23 columns]

# Data Exploration

In [17]:
df.shape

(7043, 23)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [2]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... StreamingTV  \
0  No phone service             DSL             No  ...          No   
1                No             DSL            Yes  ...          No   
2                No             DSL            Yes  ...          No   
3  No phone service             DSL            Yes  ...          No   
4                No     Fiber optic             No  ...          No   

  StreamingMovies        Contract PaperlessBilling              PaymentMethod  \
0              No  Month-to-month              Yes           Electronic check   
1              No        One year               No               Mailed check   
2              No  Month-to-month              Yes               Mailed check   
3              No        One year               No  Bank transfer (automatic)   
4              No  Month-to-month              Yes           Electronic check   

  MonthlyCharges TotalCharges numAdminTickets  numTechTickets Churn  
0          29.85        29.85               0               0    No  
1          56.95       1889.5               0               0    No  
2          53.85       108.15               0               0   Yes  
3          42.30      1840.75               0               3    No  
4          70.70       151.65               0               0   Yes  

[5 rows x 23 columns]

In [77]:
df.MultipleLines.unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [15]:
df.TotalCharges.unique()

array([29.85, 1889.5, 108.15, ..., 346.45, 306.6, 6844.5], dtype=object)

In [14]:
df.tenure.unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39])

In [13]:
df.SeniorCitizen.unique()

array([0, 1])

In [11]:
df.numAdminTickets.unique()

array([0, 1, 5, 2, 4, 3])

In [12]:
df.numTechTickets.unique()

array([0, 3, 2, 4, 1, 6, 5, 7, 8, 9])

In [36]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
numAdminTickets     0
numTechTickets      0
Churn               0
dtype: int64

# Handling Errors

In [63]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'].fillna(0, inplace=True)

<ipython-input-63-e88c90ddca19>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalCharges'].fillna(0, inplace=True)


In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [113]:
df['MultipleLines']=df['MultipleLines'].replace('No phone service','No')

In [65]:
df.customerID.duplicated().sum()

0

# Ask Questions

> max monthly charge

> number of customers

> sum of total charges

> number of customers by payment method

> total charges by payment method

> number of customers by gender

> number of customers by internet service

> total charge by internet service

> total charge and number of customers by contract type

>
















In [80]:
df['MonthlyCharges'].max()

118.75

In [81]:
CustomerNo=df['customerID'].count()
CustomerNo

7043

In [82]:
TotalCharges =sum(df['TotalCharges'])
TotalCharges

16056168.700000027

In [83]:
df.groupby('PaymentMethod')['customerID'].count()

PaymentMethod
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Electronic check             2365
Mailed check                 1612
Name: customerID, dtype: int64

In [84]:
df.groupby('PaymentMethod')['TotalCharges'].sum().sort_values(ascending=False)

PaymentMethod
Electronic check             4944903.25
Bank transfer (automatic)    4748279.90
Credit card (automatic)      4671593.35
Mailed check                 1691392.20
Name: TotalCharges, dtype: float64

In [85]:
df.groupby('gender')['customerID'].count()

gender
Female    3488
Male      3555
Name: customerID, dtype: int64

In [86]:
df.groupby('InternetService')['customerID'].count()

InternetService
DSL            2421
Fiber optic    3096
No             1526
Name: customerID, dtype: int64

In [90]:
df.groupby('InternetService')['TotalCharges'].sum().sort_values(ascending=False)

InternetService
Fiber optic    9923622.95
DSL            5121410.85
No             1011134.90
Name: TotalCharges, dtype: float64

In [107]:
df.groupby('Contract').agg(
    CustomerNo=('customerID', 'count'),
    TotalCharge=('TotalCharges', 'sum')
)

CustomerNo  TotalCharge
Contract                               
Month-to-month        3875    5305861.5
One year              1473    4467053.5
Two year              1695    6283253.7

In [112]:
df.groupby(['InternetService','Contract']).agg(customerNo=('customerID','count'),
TotalCharge=('TotalCharges','sum')).sort_values(by='TotalCharge', ascending=False)


customerNo  TotalCharge
InternetService Contract                               
Fiber optic     Month-to-month        2128   4191552.55
                Two year               429   2931646.05
                One year               539   2800424.35
DSL             Two year               628   2666283.80
                One year               570   1439990.85
                Month-to-month        1223   1015136.20
No              Two year               638    685323.85
                One year               364    226638.30
                Month-to-month         524     99172.75